bitshares/bsips

bsip-0010.md
Known issues / limitations section turned into a table. Also added fiat-stablity issue as advised by tbone.
=> Known issues reformatted

bsip-0017.md
* Execute open settlements at black swan, as suggested by xeroc
* Added alternate resolution for dependent MPAs
* Added global settlement for dependent MPAs
* Extended summary
I have just posted these changes on btstalk as well.
=> Bsip 0017, modifications and clarifications 

README.md, bsip-0019.md
BSIP-019 Draft: "Introducing profit sharing/dividends to Bitshares"
=> BSIP-019 Draft: "Introducing profit sharing/dividends to Bitshares"

README.md, bsip-0019.md, bsip-0020.md, bsip-0021.md, bsip-0022.md
BSIP 19 updated.
BSIPs 20, 21 & 22 initial commit.
=> Clean commit - BSIPs 19, 20, 21 & 22.

BSIP-0023.md, BSIP-0024.md, README.md, bsip-0019.md, bsip-0020.md, bsip-0021.md, bsip-0022.md
BSIP-0023 - Sharedropping an UIA against an external cryptocurrency distribution snapshot
BSIP-0024 - "Locking Bitshares away as 'Bitshares Influence' for voting privileges on the BTS DEX"
=> New BSIPs 23 & 24

README.md, bsip-0030.md
BSIP for https://github.com/bitshares/bitshares-core/issues/583 and https://github.com/bitshares/bitshares-core/issues/672.
=> Add BSIP 30: Always Allow Increasing Collateral Ratio If Debt Not Increased

bsip-0033.md
BSIP for https://github.com/bitshares/bitshares-core/issues/625 and https://github.com/bitshares/bitshares-core/issues/453.
=> Add BSIP 33: Maker Orders With Better Prices Take Precedence

README.md, bsip-0032.md
BSIP for https://github.com/bitshares/bitshares-core/issues/338.
=> Add BSIP 32: Always Match Orders At Maker Price

bsip-0037.md
https://github.com/bitshares/bitshares-core/issues/620
=> Add BSIP 37: Extend created asset names

bsip-0038.md
Don't allow new option to be set before hard fork.
=> bsip38 specification: add proposal handling

bsip-0035.md, bsip-0038.md
Clarification suggestions for BSIP 38
=> Bsip38 patch3

bsip-0042.md
and inclusion of a clear accepted/rejected state
=> Completion of this BSIP from a formal standpoint 

README.md, bsip-0041.md
=> BSIP41: Reduce MSSR of bitCNY from 1.1 to 1.05

README.md
=> Update status for HTLC

README.md
Update BSIP status & Add BSIP59-60
=> Update Status & Add BSIP Drafts

bsip-0060.md, bsip-00xx.md
Discussion: https://github.com/bitshares/bsips/issues/131
=> BSIP60: BitShares URI Scheme

README.md, bsip-0004.md, bsip-0043.md
=> BSIP-0004 obsoleted by BSIP-0043

README.md, bsip-0043.md, bsip-0044.md, bsip-0046.md, bsip-0058.md
Fix for #166 
Add new BSIPs and update status for others
=> Add New BSIPs and Update Status for Others

README.md, bsip-0058.md
This replaces the initial Potential Risks section with analysis provided by Michel Santos.
=> Update Potential Risks of BSIP58 (Global Settlement Protection Through Price Feeding)

README.md
Update README.md with new BSIP descriptions.
=> Add new BSIPs

README.md
Update README for new BSIPs and fixup title of BSIP64
=> Add BSIP70-71 Fixup BSIP64

README.md
Ready for voting:
- BSIP64
- BSIP70
=> Update README: BSIP64 and BSIP70

README.md
Assigned BSIP74 for Margin Call Fee Ratio
=> Update README with BSIP74

README.md
Updates the README for many new/updated BSIPs
=> Update README for BSIPs 47, 59, 63, 75, 76, 77

bsip-0081.md
=> BSIP81: Simple Maker-Taker Market Fees

bsip-0039.md
=> BSIP39 update: optionally auto-approve the proposal

README.md, bsip-0084.md
See [comment](https://github.com/bitshares/bsips/issues/81#issuecomment-558682944) in #81
=> Add retally_interval to BSIP-84

bsip-0085.md
=> Add BSIP85: Maker order creation fee discount

README.md, bsip-0062.md, bsip-0086.md
Signed-off-by: Stefan Schiessl <stefan.schiessl@blockchainprojectsbv.com>
=> 62 and 86 are now approved

bsip-0086.md
As per discussion in legal and PR terms.
=> Update for [0,100%] to [0,30%]

bsip-0077.md
A follow-up to #277 for BSIP77
=> BSIP77: Role of feed publishers
