bitshares/bsips

- README.md
- bsip-0031.md
BSIP for https://github.com/bitshares/bitshares-core/issues/343 and https://github.com/bitshares/bitshares-core/issues/649.
> Add BSIP 31: Update Short Position's Margin Call Price After Partially Called Or Settled

- bsip-0034.md
BSIP for https://github.com/bitshares/bitshares-core/issues/606.
> Add BSIP 34: Always Trigger Margin Call When Call Price Above Or At Price Feed

- README.md
- bsip-0035.md
BSIP for https://github.com/bitshares/bitshares-core/issues/132 and https://github.com/bitshares/bitshares-core/issues/184.
//Update: changed this BSIP to an overall solution for rounding issues, so it will also resolve https://github.com/bitshares/bitshares-core/issues/342. Title changed accordingly.
> Add BSIP 35: Mitigate Rounding Issue On Order Matching

- README.md
- bsip-0038.md
1/3 for https://github.com/bitshares/bsips/issues/51.
> BSIP 38: add target CR option to short positions

- README.md
- bsip-0021.md
- bsip-0022.md
- bsip-0023.md
- bsip-0024.md
- bsip-0045.md
```
BSIP: 45
Title: Introduce 'allow use as bitasset backing collateral' flag/permission to assets
Authors: Customminer
Status: Draft
Type: Protocol
Created: N/A
Discussion:  https://github.com/bitshares/bsips/issues/80
Replaces: N/A
Superseded-By: N/A
Worker: N/A
```
> Add BSIP 45 - "Introduce 'allow use as bitasset backing collateral' flag/permission to assets"

- README.md
- bsip-0043.md
PR for #102 
According to the comments: https://github.com/bitshares/bsips/issues/102#issuecomment-416565443
> What is the reasoning to have a seperate "asset_claim_reward_operation", and not funnel it through existing referral reward mechnism?
A separate account_reward_object and asset_claim_reward_operation are needed to track profits from "market fee sharing".
Vesting_balance_object receives fee from all transactions.
> The market_sharing_whitelist allows discrimination. Is there a viable use-case for this?
The market_sharing_whitelist is an additional functionality. Asset Issuer may not use this list.
> Agreed to the points above, making this a general dividend for holding the asset would be misleading the intent
We have read a few times and we're not sure we understand points 2 and 3 …
> bsip#43 Market fee sharing

- bsip-0044.md
This PR fixes a few "bugs" in the HTLC BSIP. 
Comments from @abitmore that require more discussion: 
https://github.com/bitshares/bsips/pull/104#pullrequestreview-164386716
Specifically:
1) Whether (and when) HTLCs should obey whitelisting/blacklisting
2) Risk of exposing preimage if there is a badly-timed chain reorganization or transaction censoring
3) How the summary should be worded (shortened).
Please discuss the changes made, Abit's concerns, and anything else you see that should be fixed below.
> grammar fixes BSIP 44 (HTLC)

- README.md
- bsip-0058.md
Please use this [Discussion](https://github.com/bitshares/bsips/issues/135) to add comments (not within this PR).
> Add BSIP58

- bsip-0040.md
> BSIP40: change operation_id to operation_type

- bsip-0059.md
> BSIP59: Adjustment of MSSR and MCR through voting

- README.md
All stealth BSIPs are in issues at the moment in draft status. This pull request fix the links on the main table to point to this issues for reference.
> update stealth bsip links

- bsip-0069.md
> PR for BSIP 69 "Assert Predicates"

- bsip-0072.md
Pretty render available [here](https://github.com/nathanhourt/bsips/blob/master/bsip-0072.md)
For reference, the issue is https://github.com/bitshares/bsips/issues/178.
> Add BSIP 72: Tanks and Taps

- bsip-0064.md
This BSIP will remove the requirement of a preimage length (making it optional), and adding an additional hash algorithm.
This PR fixes Issue https://github.com/bitshares/bsips/issues/163
> BSIP 64: Optional HTLC Preimage Length and Add Hash160 Algorithm

- bsip-0070.md
Related to #189 to harmonize inconsistencies about early loan closure
> BSIP70: Harmonizing early loan closure

- bsip-0073.md
- bsip-settle-order.md
> BSIP73: Match force-settlement orders with margin calls and limit orders

- bsip-0071.md
> BSIP71: Add "Prevent Global Settlement" Flag for Smartcoin

- README.md
- bsip-0047.md
This BSIP comes together with a pull request for a [**proposed** implementation](https://github.com/bitshares/bitshares-core/pull/1367).
It is sponsored by Blockchain Projects BV
> BSIP47 - An explicit voting operation

- bsip-0076.md
> BSIP 76: Threshold for price feeds through voting

- bsip-0060.md
Due to historical reasons the reference wallet and some blockchain explorers implemented `market/asset_asset` scheme, so I think it's better to stick with it. E.G.
* https://wallet.bitshares.org/#/market/BTS_CNY
* https://bts.ai/market/BTS_CNY
* https://cryptofresh.com/a/BTS_CNY
> Update market URI in BSIP60

- bsip-0083.md
Update: The current text is being revised based on discussions with the community including the Committee, and will be updated in the future
> BSIP83: Decouple BitAssets from Platform Governance Process

- bsip-0084.md
> BSIP-84: Token-based voting

- bsip-0086.md
- bsip-new.md
> BSIP 86: Share market fees to the network

- README.md
- bsip-0077.md
> BSIP77: Require Higher CR When Creating/Adjusting Debt Positions

- bsip-0081.md
It's found that the specification was not clear enough.
See also: https://github.com/bitshares/bitshares-core/pull/2136#issuecomment-613768577
> Update specification and wording of BSIP 81

- README.md
I noticed there are several bsips that still have the issue link even if their documents are finalized and merged.
> Add merged bsips to main table

- bsip-0075.md
> BSIP 75 - Asset Owner defines MCR and MSSR values

- bsip-0074.md
Rewrite spec to match implementation.
> Rewrite BSIP74 Specification section

- bsip-0077.md
Adding a permission to update the new initial collateral ratio (ICR) parameter in the same spirit as the [discussion](https://github.com/bitshares/bsips/pull/218#issuecomment-628882624) in #218
> BSIP77: Permissions and their forfeiture

- README.md
- bsip-0074.md
- bsip-0077.md
- bsip-0081.md
- bsip-0085.md
- bsip-0087.md
They had been approved for months, although at this moment their votes are below `refund400k`.
> Update status of several BSIPs
